import java.util.Map
import java.util.List
import java.time.LocalDateTime;
import java.lang.Object;
global java.time.LocalDateTime currentDateTime;

rule "BengaluruCityRenameRule_kan"
when
    $jsonData: Map(this["city"] != null)
    $cityItem: Map(
        this.containsKey("language") &&
        this.containsKey("value") &&
        this["language"] == "kan" &&
        this["value"] == "ಬೆಂಗಳೂರು"
    ) from (List) $jsonData["city"]
then
    System.out.println("Rule fired kan: BengaluruCityRenameRule_kan");
    $cityItem.put("value", "Bengaluru");
    update($jsonData);
end
